### ISSUE TITLE
New palette when only using two colours

### ISSUE THREAD

**Issue by lee-bunce** [DataScienceScotland/sgplot#4]
The main palette in the colours guidance is [Dark Blue, Turquoise, Dark Pink, Orange, Dark Grey, Light Purple], in that order.

When only using two colours however, it recommends [Dark Blue, Orange].

Add scale_colour_discrete2 and scale_colour_fill2 functions to implement this?

**Comment by alicebyers5** [comment]
Rather than add new functions for use of two colours, I've added a palette called `main2` that just includes dark blue and orange. If a chart requiring two colours uses a different `main..` palette, then a warning is generated to direct them to use `main2`. We can make sure to include something about this in the documentation too. Does that seem ok?
